### ISSUE TITLE
SWIFT_VERSION

### ISSUE THREAD

**Issue by Gorniv** [GigaDroid/flutter_udid#10]
- `flutter_udid` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or
    set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by Gorniv** [comment]
`export SWIFT_VERSION=4.0`
help me

**Comment by Gorniv** [comment]
I added a swift file to my project to solve the problem.

**Comment by lohanbodevan** [comment]
Hi @Gorniv do you mind to give more details about how did you solve this problem? Export the `SWIFT_VERSION ` variable didn't didn't work for me. 

Thanks

**Comment by Gorniv** [comment]
@lohanbodevan I added a swift file to my project.

**Comment by lohanbodevan** [comment]
@Gorniv Yes, i saw you have said it before, but i didn't understand what you meant by `I added a swift file to my project.`

Anyway i solved adding `config.build_settings['SWIFT_VERSION'] = '4.0'` to `post_install` instruction in the `ios/Podfile`.

Like this:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.0'  # <-- this thing did the trick
    end
  end
end
```

If someone knows a better way to solve feel free to comment.
Thanks!

**Comment by Gorniv** [comment]
@lohanbodevan If you add the swift file in XCode - XCode change settings XCode project automatic

`ios/Runner.xcodeproj/project.pbxproj`
![image](https://user-images.githubusercontent.com/963316/59012346-ef436780-883f-11e9-8d17-47c5b06c1ac7.png)
