### ISSUE TITLE
Can unique id change with system update?

### ISSUE THREAD

**Issue by sayhicoelho** [GigaDroid/flutter_udid#11]
Hi, thanks for sharing this awesome lib. But i'm afraid to use it in production because I don't know how it would behave if the user device gets updated (like operational system, my app version, etc.).

Would the unique id change with the system update? For example:

1. User installed my app using Android 7;
2. The app gets some unique id like (using consistent): a8e4df7ff2e2abaf2dd081fbea35183533342e8b2c8dfa2cd1acea2c1ed640eb;
3. User updates his Android version to 8.1;
4. Here is the question: Would the unique id change? The unique id will be the same?

Thanks in advance!

Great lib!

**Comment by GigaDroid** [comment]
Hi, updating the app version won't change the UUID and usually a system update won't change it either. The only case where the UUID will change is the user updating his device to Android 8 and deciding to uninstall and reinstall the app.
