### ISSUE TITLE
Migrate project to AndroidX

### ISSUE THREAD

**Issue by ernestomar** [GigaDroid/flutter_udid#12]
Is possible update the project to AndroidX?

**Comment by alexbaforvo** [comment]
This is the only plugin I have found that returns the same UDID for an iOS device across multiple installations of my app.

With every other plugin, using the 'identifierForVendor', the returning UDID changes if you reinstall the app. So this plugin is very important for my app.

But is not compatible with AndroidX, is possible to update it?

**Comment by GigaDroid** [comment]
The latest release is now migrated to AndroidX
