### ISSUE TITLE
No implementation found for method getUDID on channel flutter_udid

### ISSUE THREAD

**Issue by Xgamefactory** [GigaDroid/flutter_udid#14]
`E/flutter (18333): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getUDID on channel flutter_udid)
`

**Comment by GigaDroid** [comment]
Please add more information to this issue. Based on the information you gave, I would recommend you to use `flutter clean` and then try to run your app again.

**Comment by herrytco** [comment]
I experience the same problem when I build the release AAB of my Flutter app. I tried building it locally and on Codemagic.io with the same result.

The calling piece of code looks like this:
```
static Future<String> getId() async {
    String udid = await FlutterUdid.udid;
    return BasicHelper.getSha256(udid);
}
```

The output of flutter doctor: 

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.804], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.   
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
