### ISSUE TITLE
Cocoapod issue

### ISSUE THREAD

**Issue by utsavstha** [GigaDroid/flutter_udid#17]
I'm getting this error when I try to run my application in iOS.

_The Swift pod `flutter_udid` depends upon `SAMKeychain`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies._

**Comment by marco2250** [comment]
@utsavstha I am also getting the same error!

I would love to use this package on iPhone as well.

**Comment by marco2250** [comment]
> I'm getting this error when I try to run my application in iOS.
> 
> _The Swift pod `flutter_udid` depends upon `SAMKeychain`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies._

@utsavstha I am also getting the same error!

I would love to use this package on iPhone as wel

**Comment by babang1da** [comment]
same error!

**Comment by marco2250** [comment]
@GigaDroid Please, any news on this? Thank you

**Comment by GigaDroid** [comment]
This problem is caused by trying to use a Swift plugin in a project which has been created without Swift support, see flutter/flutter#16049 . Please follow the advice mentioned there to fix this.
