### ISSUE TITLE
error in pod

### ISSUE THREAD

**Issue by NewITCorp** [GigaDroid/flutter_udid#2]
Hi, i got an error 

The Swift pod `flutter_udid` depends upon `SAMKeychain`, which do not define modules.

please advise what to do.
in android it has no problem.

thanks

**Comment by ragasubekti** [comment]
Same problem, the problem also occurs when using use_modular_headers! in pod file

**Comment by GigaDroid** [comment]
I'm sorry, I don't quite understand what you mean.
I ran the example using the latest flutter version and it still works, I also checked the .podspec.
Please add further information.

**Comment by tje3d** [comment]
Same prob here:
```
[!] The following Swift pods cannot yet be integrated as static libraries:

    The Swift pod `flutter_udid` depends upon `SAMKeychain`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies
```

**Comment by GigaDroid** [comment]
Okay I'm still not able to replicate this. What is your CocoaPods and Flutter version?

**Comment by ragasubekti** [comment]
I honestly have no idea, [but here's the log](https://gist.github.com/ragasubekti/a6dfd51206db42ec7460467ed8c6c453)

Flutter 0.9.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f37c235c32 (3 weeks ago) • 2018-09-25 17:45:40 -0400
Engine • revision 74625aed32
Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044

**Comment by emaddoma** [comment]
I attempted to get around this error by manually adding SAMKeyChain to the PodFile, but this is the error I ran into...

> The target “flutter_udid” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.
> 
> Use Xcode 8.x to migrate the code to Swift 3.

I initialized my project with Objective-C, so I'm not sure if that is related.

**Comment by almeynman** [comment]
To fix this follow https://github.com/flutter/flutter/issues/16049#issuecomment-382629492

**Comment by elricym** [comment]
I have to mention that Firebase messaging requires to delete "use_framework!" in podfile, which is a deadlock with this plugin. I would have to ask @GigaDroid if you can bypass the dependency of "SAMKeyChain".

**Comment by StefanoGR** [comment]
No answer.. this is a bit blocking for me too....

**Comment by armandsLa** [comment]
Having the same issue. I managed to install pods by adding:
```
pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    s.swift_version = '4.2' unless s.swift_version
  end
end
```
and `use_modular_headers!`, but `flutter run` fails. Looks like this plugin is not supporting projects built with Objective-C instead of Swift.

**Comment by GigaDroid** [comment]
This apparently is indeed a problem caused by projects using Objective-C while this plugin is using swift. I can't do anything else than wait for the flutter team to fix this. Please upvote the already mentioned issue at flutter/flutter#16049

**Comment by elricym** [comment]
FYI, Firebase Messaging no long requires "use_framework!" in recent versions. There is no more conflicts with it.
