### ISSUE TITLE
cocopod : Error running pod install

### ISSUE THREAD

**Issue by jayantsr** [GigaDroid/flutter_udid#21]
Error When using flutter_udid package.

If remove it from pubspec.yaml it works fine .  Please help

Launching lib/main.dart on Iphone XR in debug mode...
Running pod install...
CocoaPods' output:
↳
Exited (sigterm)
Error running pod install

**Comment by GigaDroid** [comment]
Sorry, I didn't have time to continue working on this plugin during the past months. If you still weren't able to solve this problem, please reopen.
