### ISSUE TITLE
UDID changes after updating the application

### ISSUE THREAD

**Issue by Kacper1263** [GigaDroid/flutter_udid#22]
Does this plugin still work? After application update my UDID changes. I have Android 10 and after building new version of my app all UDIDs are changing.

**Comment by leonpflegia** [comment]
This plugin is using SSAID for Android, which is still supported in Android 10. See more information here: `https://developer.android.com/training/articles/user-data-ids#signed-out-user-prefs-between-apps` 
Are you sure you are using the same signing key?

**Comment by GigaDroid** [comment]
This plugin is using SSAID for Android, which is still supported in Android 10. See more information here: https://developer.android.com/training/articles/user-data-ids#signed-out-user-prefs-between-apps
Are you sure you are using the same signing key?

**Comment by Kacper1263** [comment]
> Are you sure you are using the same signing key?

I think that was my problem. I was testing the ID between the Google version (with overwritten signing key) and new release build version with my own key. I quickly downloaded the version from Google again and everything seems to work. Thanks for your help and sorry for my mistake. I am closing :)
