### ISSUE TITLE
Use UDID for device token APNS

### ISSUE THREAD

**Issue by devglrd** [GigaDroid/flutter_udid#28]
Hello,

I'm asking myself a question, can we use the UDID wich generate by this plugin, for device token parameter of api call at APNS endpoint for display notification in ios device ?

I use this, and APNS return me BadDeviceToken

Thanks for your advice.

**Comment by GigaDroid** [comment]
Hey, you can't use the UDID for APNS, you have to use the token you receive upon registering the device for remote notifications.

**Comment by devglrd** [comment]
Okey so i have some question... 

How we register device for remote notification ?
We have to do for any user use my application ?

**Comment by GigaDroid** [comment]
This is a question not related to this plugin. Please take a look at the documentation provided by Apple or by flutter plugins relying on APNS. https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns
