### ISSUE TITLE
Unable to determine Swift version for the following pods

### ISSUE THREAD

**Issue by mastahed** [GigaDroid/flutter_udid#3]
Error appears when getting dependencies. Part of the log below.

> CocoaPod version: 1.6.0.beta.2

`Installing flutter_udid (0.0.1)
  Running pre install hooks
  Unable to determine Swift version for the following pods 

flutter_udid does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.`

**Comment by richardcarmichael** [comment]
Hi @mastahed - I'm having same problem. Did you resolve the issue? What was the solution?

**Comment by richardcarmichael** [comment]
Solved it - Adding an empty Swift file to your Flutter iOS (runner) project in Xcode and accepting to add bridging header fixed it.

**Comment by luisgcs** [comment]
> Solved it - Adding an empty Swift file to your Flutter iOS (runner) project in Xcode and accepting to add bridging header fixed it.

Can you show the code?
