### ISSUE TITLE
UDID Is changing everywhile

### ISSUE THREAD

**Issue by AhmedMahhmoud** [GigaDroid/flutter_udid#30]
I am working on an application where i must store a unique id for the device for my users. 
but after app updates the udid sometimes changes (i didn't upgrade my mobile device version)

**Comment by AhmedMahhmoud** [comment]
i found the problem that release version generates udid different from the debug version

**Comment by GigaDroid** [comment]
The plugin relies on the signing keys to generate the UDID and the release and debug signing keys are different
