### ISSUE TITLE
Will the UDID not change after an upgrade app version

### ISSUE THREAD

**Issue by WONDERJEWEL** [GigaDroid/flutter_udid#34]
I'm using UDID to identify the device.
I saved the UDID on signup.
Is it going to be the same UDID after I will upgrade the app version?

**Comment by aliev-sergey** [comment]
Actually it should be the same. I don't remember a time where I needed to change the UDID on developer.apple.com for test purposes

**Comment by appinteractive** [comment]
It does persist. Using it in production and it does its job 👍

**Comment by GigaDroid** [comment]
Sorry for the late response, yes I can confirm that it's going to be the same, even after there has been an update to your app.
