### ISSUE TITLE
Is this package compliant with Google Play Families Policy Requirements? 

### ISSUE THREAD

**Issue by jakobhec** [GigaDroid/flutter_udid#35]
I would like to use this package in an app, but [Google Play Families Policy Requirements](https://support.google.com/googleplay/android-developer/answer/9893335#families-policy) states: 

> Apps that target both children and older audiences must not transmit AAID, SIM Serial, Build Serial, BSSID, MAC, SSID, IMEI, and/or IMSI from children or users of unknown age.

I don't know how these IDs relate to flutter_udid. Am I allowed to transmit the string obtained using the following code? 
```
import 'package:flutter_udid/flutter_udid.dart';
String udid = await FlutterUdid.udid;
```

**Comment by GigaDroid** [comment]
Reading the documentation regarding the requirements, it appears as if the ANDROID_ID is allowed to be transmitted, but you have to disclose the transmission of such sensitive data to your users. To be sure, please contact the Google Play developer support.
