### ISSUE TITLE
Lexical or Preprocessor Issue (Xcode): 'flutter_udid/flutter_udid-Swift.h' file not found

### ISSUE THREAD

**Issue by HassanButt2022** [GigaDroid/flutter_udid#40]
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'flutter_udid/flutter_udid-Swift.h' file not found
/Users/user/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_udid-2.0.1/ios/Classes/FlutterUdidPlugin.m:1:8

**Comment by GigaDroid** [comment]
Can you try running `flutter clean` and build your app again. As this is a quite old issue, and not reproducible for me I'm closing this for now. Feel free to reopen in case this error still occurs.
