### ISSUE TITLE
A problem occurred configuring project ':flutter_udid'

### ISSUE THREAD

**Issue by DeepeshKalura** [GigaDroid/flutter_udid#41]
- The error message:

A problem occurred configuring project ':flutter_udid'.

Could not load compiled classes for build file 'C:\Users\deepe\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_udid-2.0.1&lt;0>android\build.gradle' from cache.
Failed to notify project evaluation listener.
Could not get unknown property 'android' for project ':flutter_udid' of type org.gradle.api.Project.
Could not get unknown property 'android' for project ':flutter_udid' of type org.gradle.api.Project.

![Error Image](https://github.com/GigaDroid/flutter_udid/assets/99230888/2af0bf57-984d-4d33-a96d-4bd8c1cabe2a)

- Development Environment

The Flutter SDK version: 3.7.11 
The vs code version: 1.81.0
The operating system: windows 11

The expected behavior: The build should succeed without any errors.

**Comment by GigaDroid** [comment]
Can you try running `flutter clean` and build your app again? As this is a quite old issue, and not reproducible for me I'm closing this for now. Feel free to reopen in case this error still occurs.
