### ISSUE TITLE
Windows & Linux support

### ISSUE THREAD

**Issue by fotiDim** [GigaDroid/flutter_udid#49]
Are there any plans for Windows & Linux support? It should be straightforward to add support for those when adding another package as a dependency. We are willing to file PRs if that is of interest.

**Comment by GigaDroid** [comment]
Hey, I don't have time to implement Windows & Linux at the moment, but will review the PR if you create one!

**Comment by GigaDroid** [comment]
Thanks for the PR. Version with Windows & Linux support has just been released.
