### ISSUE TITLE
linux, Permission denied

### ISSUE THREAD

**Issue by huanguan1978** [GigaDroid/flutter_udid#55]
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
Can't read memory from /dev/mem
--
Is it possible to use a machine ID similar to device_info_plus in Linux?

**Comment by GigaDroid** [comment]
Hey, yes I see the issue with the current approach, it would make sense to rely on the machine ID instead. I currently do not have access to a device running linux. Would you be able to implement this and create a PR for it?

**Comment by huanguan1978** [comment]
Processed, please merge the code.
